### ISSUE TITLE
add lazy version?

### ISSUE THREAD

**Issue by lukewestby** [ajwhite/render-if#1]
Would you be willing to consider a lazy version of `renderIf` that accepts a thunk rather than a materialized component? I can submit a PR if you'd be interested.

```javascript
const renderIfLazy = (predicate) => (componentThunk) => {
  // maybe throw if componentThunk isn't a function
  return predicate && componentThunk();
}
```

Thanks!

**Comment by ajwhite** [comment]
At first I was going to say we can simply check if the curried argument is a `function`, but I believe the component provided is considered a function, right? If not, we could just do a function check and invoke it 

```js
const isFunction = input => typeof input === 'function';
predicate => component => predicate ? isFunction(component) ? component() : component : null;
```

If a `<JsxEelement />` is considered a `typeof` `function` then a second `renderIfLazy` sounds like the way to go

**Comment by lukewestby** [comment]
Checking the type of the argument seems like it should work. [If I follow the terminology correctly](https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html), what we're differentiating is a function versus an `element`, which is always just a plain object. +1 from me for detecting type and chosing behavior accordingly!

**Comment by ajwhite** [comment]
I dig it. If you need this sooner than later, feel free to submit a PR, otherwise I can throw one up later this week

**Comment by lukewestby** [comment]
Done! #2 

Thanks!!

**Comment by felixgirault** [comment]
Hi, 
Sorry to comment on a closed issue, but I wanted to let you know we made an eslint plugin to enforce usage of the lazy version https://github.com/v-technologies/eslint-plugin-render-if, if it could be of any interest to someone ;)
