### ISSUE TITLE
Remove .bablerc

### ISSUE THREAD

**Issue by ajwhite** [ajwhite/render-if#3]
`.babelrc` is used to compile the ES6 file into an ES5 for `npm` publishing.

The problem arises when the React Packager needs to import this module, it also reads `.bablerc` and notices that the required babel plugin doesn't exist (`babel-plugin-add-module-exports`).

As this is really only used to compile the the module, we don't need a `babelrc` file. I can just update `npm compile` to also use `--presets es2015 --plugins add-module-exports`.

This was discovered and reported over twitter https://twitter.com/stratospher_es/status/707265585319645184

**Comment by mrpatiwi** [comment]
I'm having problems with React Native for this same reason.

**Comment by ajwhite** [comment]
Should be all set now @mrpatiwi. If you install `0.1.1`, this will no longer include the `.bablerc` file. This has now been excluded from the published npm package.

**Comment by stratospheres** [comment]
Awesome! Thanks for doing this!
