### ISSUE TITLE
Can I use it with React Native?

### ISSUE THREAD

**Issue by benjaminb10** [ajwhite/render-if#8]

**Comment by ajwhite** [comment]
Of course! If you take a look at [the code](https://github.com/ajwhite/render-if/blob/master/renderIf.js), it's all very simple and platform agnostic; it's simply performs some basic logic to see if the first value is `true`, and then returns the second value; otherwise null.

```
renderIf(true)("foo") // returns "foo"
renderIf(false)("foo") // returns null
```
